name: symptom_checker
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  after_layout: ^1.2.0
  animations: ^2.0.8
  cupertino_icons: ^1.0.2
  connectivity_plus: ^2.2.1
  csv: ^5.0.2
  flutter_launcher_icons: ^0.13.1
  get: ^4.6.5
  http: ^1.1.0
  provider: ^6.0.5
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/splash.jpg"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/csv/
    - assets/images/
